<?php

/**
 * @file
 * Contains custom_gutenberg.module.
 */

/**
 * Implements hook_gutenberg_blocks().
 */
function custom_gutenberg_gutenberg_blocks() {
  return [
    'custom-gutenberg/my-custom-block' => [
      'attributes' => [
        'content' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],

//custom_gutenberg always stays the same but after the slash you put the name of the card you are adding
'custom-gutenberg/uis-card' => [
  "attributes" => [
        'headerText' => [
          'type' => 'string',
        ],
        'title' => [
          'type' => 'string',
        ],
        'content' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],
      ];
}




//Should never need to touch these
/**
 * Implements hook_library_info_alter().
 */
function custom_gutenberg_library_info_alter(&$libraries, $extension) {
  if ($extension === 'gutenberg') {
    $libraries['editor']['dependencies'][] = 'custom_gutenberg/custom_gutenberg_blocks';
  }
}

/**
 * Implements hook_gutenberg_editor_assets().
 */
function custom_gutenberg_gutenberg_editor_assets() {
  return [
    'custom_gutenberg/custom_gutenberg_blocks',
  ];
}